

```{r}
library(tidyverse) 
library(tidytext) 
media = read_csv("~/shared/minor2_2018/2-tm-net/lab03-tm/media.csv") 

```

```{r}
media$text = str_replace_all(media$text, "[[:digit:]]", "")
media_words = media %>% tidytext::unnest_tokens(words, text)
 
rustopwords <- data.frame(words=stopwords::stopwords("ru"), stringsAsFactors=FALSE)
media_words = media_words %>% anti_join(rustopwords)

media_words_count = media_words %>% dplyr::count(words) %>% filter(n > 2 & n < quantile(n, 0.99))
median(media_words_count$n)
```
```{r}
long_text = media_words %>% group_by(media) %>% summarise(n = n())
long_text = long_text %>% filter(n >= 6)

long_media = media_words %>% filter(media %in% long_text$media) %>% filter(words != "br")

long_media = long_media %>% dplyr::count(media, words)

media_tf_tdf = long_media %>% bind_tf_idf(words, media, n) %>% arrange(-tf_idf)
media_tf_tdf = media_tf_tdf %>% group_by(words) %>% summarise(tf_idf = mean(tf_idf)) %>% arrange(-tf_idf)
```

```{r}
c = c(
 "суток",
 "побои",
 "шоу",
 "фбк",
 "иностранным",
 "харбин")

media_tf_tdf = media_tf_tdf %>% filter(words %in% c)
media_tf_tdf %>% arrange(-tf_idf)
```


```{r}




```

```{r}
rbc <- read_csv("~/shared/minor2_2018/data/rbc.csv")

#Удалите числа и пунктуацию, а желательно привести слова к нижнему регистру. 
rbc$text = str_replace_all(rbc$text, '[[:space:]]+', ' ') #дополнительно удалите лишние пробелы

#Вызовем mystem
text.tmp <- system2("mystem", c("-c", "-l", "-d"), input = rbc$text, stdout=TRUE) 
#Почистим полученный аутпут 

text.lem <- str_replace_all(text.tmp, "\\{([^}]+?)([?]+)?\\}", "\\1")
rbc <- cbind(rbc, lem = text.lem)
rbc$lem = as.character(rbc$lem)

rbc %>% tidytext::unnest_tokens(words, text) %>% distinct(words)

rbc %>% tidytext::unnest_tokens(words, lem) %>% distinct(words)
#879
#674
879 - 674

```

```{r}
rbc_vk = read_csv("~/shared/minor2_2018/data/rbc_vk.csv") 
#в колонке lem мы записали тексты новостей уже в лемматизированной форме. приведите по этой колонке данные в длинный формат
rbc_vk = rbc_vk %>% unnest_tokens(words, lem)
rbc_vk = rbc_vk %>% anti_join(rustopwords)
rbc_vk = rbc_vk %>% filter(!str_detect(rbc_vk$words, "[A-z]"))

#удалите слова, встречающиеся меньше 15 или больше 30 раз
rbc_vk_word = rbc_vk %>% dplyr::count(words) %>% filter(n < 15 | n > 30)
rbc_vk = rbc_vk %>% filter(words %in% rbc_vk_word$words)
#удалите тексты, в которых встречается 5 и меньше слов
rbc_vk_id = rbc_vk %>% dplyr::count(id) %>% filter(n>5)
rbc_vk = rbc_vk %>% filter(id %in% rbc_vk_id$id)
rbc_vk = rbc_vk %>% dplyr::count(id, words)
#посчитайте взвешенную частотность слов с bind_tf_idf() и создайте term-document matrix
rbc_vk_tf_idf = rbc_vk %>% bind_tf_idf(words, id, n)



rbc_vk_tf_idf$idduy = rbc_vk_tf_idf$id
rbc_vk_tf_idf = rbc_vk_tf_idf %>% select(-id)
library(tidyr)
rbc.tdm = rbc_vk_tf_idf %>%
    dplyr::select(idduy, words, tf_idf) %>%
    spread(words, tf_idf, fill = 0)

rownames(rbc.tdm) =  rbc.tdm$idduy #присвоим строкам названия -- id постов в вк

rbc.tdm = rbc.tdm %>% select(-idduy)
rbc.tdm = rbc.tdm %>% as.matrix()

c = c(4788911,
 4786323,
 4789051,
 4783509)
rbc_test1 = rbc.tdm %>% filter(idduy == 4788911)
rbc_test2 = rbc.tdm %>% filter(idduy == 4786323)
rbc_test3 = rbc.tdm %>% filter(idduy == 4789051)
rbc_test4 = rbc.tdm %>% filter(idduy == 4783509)
# 4788911 %in% rbc.tdm$idduy

test_tdm = rbind(rbc_test1, rbc_test2, rbc_test3, rbc_test4)

lsa::cosine(t(test_tdm))

```


```{r}



rbc_cosine = lsa::cosine(rbc_tdm %>% t())

```



```{r}
rbc_vk = read_csv("~/shared/minor2_2018/data/rbc_vk.csv") 
#в колонке lem мы записали тексты новостей уже в лемматизированной форме. приведите по этой колонке данные в длинный формат
#удалите слова, встречающиеся меньше 15 или больше 30 раз
#удалите тексты, в которых встречается 5 и меньше слов
#посчитайте взвешенную частотность слов с bind_tf_idf() и создайте term-document matrix

#многие фукнции могут требовать, чтобы на входе была именно матрица. для этого 

rownames(rbc.tdm) =  rbc.tdm$id #присвоим строкам названия -- id постов в вк 

rbc.tdm = rbc.tdm %>% select(-id)
rbc.tdm = rbc.tdm %>% as.matrix()
```

