
```{r}
library(dplyr)
```

```{r}
movies <- read_csv("~/shared/minor2_2018/data/movies_cut.csv")
ratings <- read_csv("~/shared/minor2_2018/data/ratings_cut.csv")
ratings=ratings %>% group_by(movie_id, movie_year) %>% summarise(rating = mean(rating,na.rm = T))
movies = left_join(movies, ratings, by = "movie_id")
movies = movies %>% select(-X1)
```

```{r}
library(stringr)
clear_punc = function(text) {
  text = str_remove(text, '\\[')
  text = str_remove(text, '\\]')
  text = str_remove_all(text, "\"")
  text = str_replace_all(text, " ", "-")
  return(text)
}
```



```{r}
library(RCurl)
library(XML)
library(rjson)
library(stringr)
library(tm)

# Это функция, которая взять данные о главных актерах/актрисях из сайта metacritic (https://www.metacritic.com/movie/batman-begins/details). Input: Название фиьлма, Output: главные актеры

# Внимание: не попробуйте эту функцию для длинного вектора названия фиьлмы. Потому что функция медленно работает (примерно 3 секунды за фильм), если длина вектор названия = 500, то время будет ~ 1500s ... Когда получится main_cast надо сохранить датафраме сразу (write.csv)

get_director = function(title) {
  title = removePunctuation(title)
  title = stringr::str_to_lower(title)
  title = stringr::str_split(title, " ")[[1]]
  title = stringr::str_c(title, collapse = "-")
  link = stringr::str_c("https://www.metacritic.com/movie", title, "details", sep = "/")
  # link = "https://www.metacritic.com/movie/batman-begins/details"
  webpage <- RCurl::getURL(link)
  if (webpage == "") { return(NA)}
  else {
    webpage <- readLines(tc <- textConnection(webpage)); close(tc)
    pagetree <- XML::htmlTreeParse(webpage, error=function(...){}, useInternalNodes = TRUE)
    # parse the tree by tables
    x <- xpathSApply(pagetree, "//*/table", xmlValue)
    
    if (length(x)==0) {return(NA)}
    else{
    # do some clean up with regular expressions
    x <- unlist(strsplit(x, "\n"))
    x <- gsub("\t","",x)
    x <- sub("^[[:space:]]*(.*?)[[:space:]]*$", "\\1", x, perl=TRUE)
    x <- x[!(x %in% c("", "|"))]
    m = match(c("Director", "Writer"), x)
    if (is.na(m[1]) | is.na(m[2])) {return(NA)}
    else{
    y = x[(m[1]+2):(m[2]-1)]
    y = y[seq(1, length(y), by = 2)]
    z = rjson::toJSON(y)
    return(z)}
    }
    }
}

get_director("The Love Letter")
```

```{r}
main_director = Map(get_director, movies$title) # это не ошибка, просто он медленно работает, примерно 30 минут. Поэто му я сохранил результат в датасет data_cast.csv чтобы не нужно повторить эту функцию.
save = main_director
```

```{r}
values = unlist(main_director, use.names = F)
data_director = data.frame(title = names(main_director), director = values)
data_director$director = as.character(data_director$director)
data_director$title = as.character(data_director$title)
typeof(data_director)
write.csv(data_director, "data_director.csv")
```

```{r}
library(readr)
movies <- read_csv("~/shared/minor2_2018/data/movies_cut.csv")
ratings <- read_csv("~/shared/minor2_2018/data/ratings_cut.csv")
ratings=ratings %>% group_by(movie_id, movie_year) %>% summarise(rating = mean(rating,na.rm = T))
movies = left_join(movies, ratings, by = "movie_id") %>% select(-X1)
movies2 = movies %>% dplyr::select(title, movie_id, rating, genres, popularity, runtime, movie_year, production_companies, production_countries, keywords)

data_cast = read_csv("data_cast.csv") %>% select(-X1)

movies2 = movies2 %>% left_join(data_cast, by = "title")

data_director = read_csv("data_director.csv")%>% select(-X1)
movies2 = movies2 %>% left_join(data_director, by = "title")

movies2$cast = clear_punc(movies2$cast)
movies2$director = clear_punc(movies2$director)
movies2 = distinct(movies2)
write.csv(movies2, "movies2.csv")
```


```{r}
library(readr)
movies <- read_csv("~/shared/minor2_2018/data/movies_cut.csv")
ratings <- read_csv("~/shared/minor2_2018/data/ratings_cut.csv")
ratings=ratings %>% group_by(movie_id, movie_year) %>% summarise(rating = mean(rating,na.rm = T))
movies = left_join(movies, ratings, by = "movie_id") %>% select(-X1)
movies2 = movies %>% dplyr::select(title, movie_id, rating, genres, popularity, runtime, movie_year, production_companies, production_countries, keywords)

data_cast = read_csv("data_cast.csv") %>% select(-X1)

movies2 = movies2 %>% left_join(data_cast, by = "title")

data_director = read_csv("data_director.csv")%>% select(-X1)
movies2 = movies2 %>% left_join(data_director, by = "title")

movies2$cast = clear_punc(movies2$cast)
movies2$director = clear_punc(movies2$director)
movies2 = distinct(movies2)
write.csv(movies2, "movies2.csv")
```