```{r}
library(RCurl)
library(XML)
library(rjson)
library(stringr)
library(tm)
# Это функция, которая взять данные о главных актерах/актрисях из сайта metacritic (https://www.metacritic.com/movie/batman-begins/details). Input: Название фиьлма, Output: главные актеры

# Внимание: не попробуйте эту функцию для длинного вектора названия фиьлмы. Потому что функция медленно работает (примерно 3 секунды за фильм), если длина вектор названия = 500, то время будет ~ 1500s ... Когда получится main_cast надо сохранить датафраме сразу (write.csv)

get_cast = function(title) {
  title = removePunctuation(title)
  title = stringr::str_to_lower(title)
  title = stringr::str_split(title, " ")[[1]]
  title = stringr::str_c(title, collapse = "-")
  link = stringr::str_c("https://www.metacritic.com/movie", title, "details", sep = "/")
  # link = "https://www.metacritic.com/movie/batman-begins/details"
  webpage <- RCurl::getURL(link)
  if (webpage == "") { return(NA)}
  else {
    webpage <- readLines(tc <- textConnection(webpage)); close(tc)
    pagetree <- XML::htmlTreeParse(webpage, error=function(...){}, useInternalNodes = TRUE)
    # parse the tree by tables
    x <- xpathSApply(pagetree, "//*/table", xmlValue)
    
    if (length(x)==0) {return(NA)}
    else{
    # do some clean up with regular expressions
    x <- unlist(strsplit(x, "\n"))
    x <- gsub("\t","",x)
    x <- sub("^[[:space:]]*(.*?)[[:space:]]*$", "\\1", x, perl=TRUE)
    x <- x[!(x %in% c("", "|"))]
    m = match(c("Principal Cast", "Cast"), x)
    if (is.na(m[1]) | is.na(m[2])) {return(NA)}
    else{
    y = x[(m[1]+2):(m[2]-1)]
    y = y[seq(1, length(y), by = 2)]
    z = rjson::toJSON(y)
    return(z)}
    }
    }
}

get_cast("Charly")
```

```{r}
clear_punc = function(text) {
  text = str_remove(text, '\\[')
  text = str_remove(text, '\\]')
  text = str_remove_all(text, "\"")
  return(text)
}

text = '["Ralph Fiennes","Sean Connery","Uma Thurman"]'
clear_punc(text)
```
```{r}
main_cast = Map(get_cast, movies$title)
save = main_cast
```

```{r}

values = unlist(main_cast, use.names = F)
data_cast = data.frame(title = names(main_cast), cast = values)
data_cast$cast = as.character(data_cast$cast)
data_cast$title = as.character(data_cast$title)
typeof(data_cast)

```



