---
title: "Exploratory"
output:
  html_document: default
---

## Разведочный анализ данных и постановка задачи

Мы с вами поговорили про основы разведочного аналаза данных и про основные методы обработки и агрегации данных. Еще одна часть, которую мы подробно рассмотрим чуть позже -- это проверка гипотез с помощью статистических тестов.

Сегодня вы попробуете применить ваши знания к реальным данным, про которые вы почти ничего не знаете. Это будет частью вашей домашней работы.

Загрузим необходимые данные с которыми вам предстоит работать. Ваш вариант заканчивается на НОМЕРГРУППЫ.csv:

```{r}
library(readr)
library(dplyr)
library(ggplot2)

#обращайте внимание на номер группы
airline <- read_csv("~/shared/minor2_2018/1-intro/data/airline_sub_1.csv")
airport <- read_csv("~/shared/minor2_2018/1-intro/data/airport_sub_1.csv")
lounge <-  read_csv("~/shared/minor2_2018/1-intro/data/lounge_sub_1.csv")
seat <-  read_csv("~/shared/minor2_2018/1-intro/data/seat_sub_1.csv")
```

Ваша задача расказать нам про эти данные, то что вы сможете в них увидеть. Результатом должен быть Rmd файл с вашим анализом, лучше всего если вы продолжите работать в этом файле. **Обязательно** укажите свои имя, фамилию и группу.

Сегодня вы должны понять что за данные перед вами. Построить ряд графиков, которые помогут вам охарактеризовать данные. И поставить вопросы о взаимосвязи разных переменных из датасета.

Для начала почитаем подробнее о данных:
https://github.com/quankiquanki/skytrax-reviews-dataset/blob/master/README.md

Работу нужно сдать с помощью gist. Инструкция по работе ~/shared/minor2_2018/gists.pdf

Дедлайн стоит в 23:59 21.10.2018 и называется "Майнор 2 курс 2018-2019: Разведочный анализ - авиаперевозки".

Предварительную версию вашей работы можете сдать прямо на паре. Вы сможете обновить ее в любой момент до истечения дедлайна. Проверяться будет последняя версия. 


